---
resources:
  - name: powerprotect_ansible_module
    type: git
    source:
      uri: https://github.com/EMC-Underground/powerprotect_ansible_module.git
      branch: master

jobs:
  - name: add-k8s-cluster-ppdm
    public: true
    serial: true
    plan:
      - get: powerprotect_ansible_module
      - task: add-cluster
        params:
          PASSWORD: ((ppdm_password))
          SERVER: ((ppdm_server))
          CREDNAME: ((cred_name))
          KUBEUSERNAME: ((cred_kube_username))
          KUBEADDRESS: ((kube_address))
          KUBEPASSWORD: ((ppdm_discovery_token))
          KUBENAME: ((kube_name))
          KUBEPORT: ((kube_port))
        config:
          inputs:
            - name: powerprotect_ansible_module
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpinelinux/docker-cli
              tag: latest
          run:
            path: sh
            args:
            - -c
            - |
              apk add gcc
              apk add make
              cd service-sql-repo
              ls -la
              make

